language: c

jobs:
  include:
    - os: linux
      arch: amd64
      dist: xenial
      compiler: gcc
    - os: linux
      arch: amd64
      dist: xenial
      compiler: clang
    - os: linux
      arch: amd64
      dist: bionic
      compiler: gcc
    - os: linux
      arch: amd64
      dist: bionic
      compiler: clang
    - os: linux
      arch: amd64
      dist: focal
      compiler: gcc
    - os: linux
      arch: amd64
      dist: focal
      compiler: clang
    - os: linux
      arch: ppc64le
      dist: xenial
      compiler: gcc
    - os: linux
      arch: ppc64le
      dist: xenial
      compiler: clang
    - os: linux
      arch: ppc64le
      dist: bionic
      compiler: gcc
    - os: linux
      arch: ppc64le
      dist: bionic
      compiler: clang
    - os: linux
      arch: ppc64le
      dist: focal
      compiler: gcc
    - os: linux
      arch: ppc64le
      dist: focal
      compiler: clang

sudo: false

addons:
  apt:
    packages:
      - make
      - gcc-multilib
      - libpcap0.8
      - libpcap0.8-dev

cache:
  directories:
    - $HOME/.ccache

before_script:
  - make clean

script:
  - make
  - ./xl2tpd-control --version
  - ./xl2tpd-control --help
